jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Run tests
      run: dotnet test --logger "trx;LogFileName=test-results.trx" --results-directory tests/Library.Tests.Api/bin/Debug/net8.0/test-results

    - name: List files in the test-results.zip
      run: unzip -l test-results.zip

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: tests/Library.Tests.Api/bin/Debug/net8.0/**/*.trx

    - name: Generate test report
      uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: api tests results
        path: test-results/test-results.trx  # Update path here based on artifact structure
        reporter: dotnet-trx
        fail-on-error: false
        path-replace-backslashes: false
        list-suites: all
        list-tests: all
        max-annotations: 10
        fail-on-empty: true
        only-summary: false
        token: ***

    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true