name: API Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    steps:
      # Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      # Restore .NET dependencies
      - name: Restore dependencies
        run: dotnet restore
      # Build the project
      - name: Build
        run: dotnet build
      # Run API tests
      - name: Run API tests
        run: dotnet test ${{github.workspace}}/tests/Library.Tests.Api/Library.Tests.Api.csproj --logger "trx;LogFileName=test-results.trx" --results-directory ${{github.workspace}}/tests/Library.Tests.Api/bin/Debug/net8.0/test-results
      # Upload test results as artifacts
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4.4.2
        with:
          name: test-results
          path: ${{github.workspace}}/tests/Library.Tests.Api/bin/Debug/net8.0/test-results
  test-results:
    name: Get Test Results
    runs-on: ubuntu-latest
    needs: run-api-tests
    steps:
      # Display test results using dorny/test-reporter
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always() # Always run this step, even if previous steps fail
        with:
          artifact: test-results
          name: api tests results
          path: './test-results.trx'
          reporter: dotnet-trx
          fail-on-error: false